# Generated by Django 5.1.4 on 2025-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
